### ISSUE TITLE
Is it possible to have MIT only license for this project?

### ISSUE THREAD

**Issue by alexanderkirsanov** [walling/unorm#45]
Hi, 
you created great polyfill, but it is not possible to use it in some projects due to license. Is it possible to change the license to MIT only?

**Comment by phadej** [comment]
Why? It's disjunction, you can choose to use `unorm` under **either** `MIT` **or** `GPL-2.0` terms. Not **both**.

**Comment by alexanderkirsanov** [comment]
@phadej Thanks for pointing this. I checked several articles and found the confirmation, that even if licenses joined by 'and' we can use a license which we want.

**Comment by phadej** [comment]
**No**. If the licenses are joined with `AND` you have to comply with terms of **both** licenses.

**Comment by walling** [comment]
Thanks, @phadej. The `license` field in `package.json` already reflects this correctly. Maybe someone has time to send a PR to clarify this in the README as well.

**Comment by phadej** [comment]
Can @walling confirm which operator should be there. If the project is based on Unicode Normalizer (was it GPLd?) then we should ha e `AND`; and neither can relax it

**Comment by walling** [comment]
First off, I am not a lawyer, so please do not take my findings as advice in any regard. Do you own research as well. Here's what I'm found:

The original website, where this project was forked from, is [not available at this moment](http://coderepos.org/share/browser/lang/javascript/UnicodeNormalizer). I'll check again later… here's the [project page on archive.org](https://web.archive.org/web/20161030222604/http://coderepos.org/share/browser/lang/javascript/UnicodeNormalizer), however the relevant files are not accessible.

When you go back to the first commit in this repo (the `./src` folder was directly imported from the forked SVN repo), this is the headers you find:

  - Git commit 63d85f3, file `./src/unormdata.js`:

    ```
    /*
     * UnicodeNormalizer 1.0.0
     * Copyright (c) 2008 Matsuza
     * Dual licensed under the MIT (MIT-LICENSE.txt) and GPL (GPL-LICENSE.txt) licenses.
     * $Date: 2008-06-05 16:34:31 +0200 (Thu, 05 Jun 2008) $
     * $Rev: 13307 $
     */
    ```

  - Git commit 63d85f3, file `./src/unorm.js`:

    ```
    /*
     * UnicodeNormalizer 1.0.0
     * Copyright (c) 2008 Matsuza
     * Dual licensed under the MIT (MIT-LICENSE.txt) and GPL (GPL-LICENSE.txt) licenses.
     * $Date: 2008-06-05 16:44:17 +0200 (Thu, 05 Jun 2008) $
     * $Rev: 13309 $
     */
    ```

I personally understand _dual-licensed_ as a choice between two licenses, but in some cases [it could be interpreted differently](https://en.wikipedia.org/wiki/Multi-licensing). Whether those conditions apply here or not, I'm not qualified to say.

---

A safe long-term solution that would satisfy most people would probably be a clean room re-implementation under a single license (e.g. MIT).

Another pragmatic solution is to use this code right now in your GPL licensed project, since MIT is GPL-compatiable, as far as I'm aware.

The final approach could be to interpret _dual-licensed_ as a choice between MIT or GPL, however more information is required to resolve this properly.
